import React, { useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import {
  Building2,
  ArrowRight,
  Lock,
  Mail,
  User,
  CheckCircle2,
  Globe,
  Info,
  AlertCircle,
  ShieldCheck,
  Phone,
  MapPin,
  Eye,
  EyeOff,
  Briefcase,
  KeyRound,
  GraduationCap
} from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { useNotifications } from "../../context/NotificationContext";
import { Button } from "../../components/common/Button";
import { Modal } from "../../components/common/Modal";

export function LoginPage({ initialRegisterMode = false }) {
  const { institutionLogin, changePassword, onboardUniversity } = useAuth();
  const { showSuccess, showError, showWarning, showInfo } = useNotifications();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  // Mode: Sign In vs Request Partnership
  const [isRegisterMode, setIsRegisterMode] = useState(() => {
    return initialRegisterMode || searchParams?.get("mode") === "onboard" || searchParams?.get("mode") === "partnership";
  });

  // Institutional Sign In states
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [rememberMe, setRememberMe] = useState(true);
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);

  // Mandatory First-Login Password Reset State
  const [passwordResetModalOpen, setPasswordResetModalOpen] = useState(false);
  const [resetOldPassword, setResetOldPassword] = useState("");
  const [resetNewPassword, setResetNewPassword] = useState("");
  const [resetConfirmPassword, setResetConfirmPassword] = useState("");
  const [resettingPassword, setResettingPassword] = useState(false);

  // Inbound Partnership / Briefing Form states
  const [inquiryForm, setInquiryForm] = useState({
    name: "",
    code: "",
    officialEmail: "",
    address: "",
    city: "",
    state: "",
    country: "India",
    website: "",
    phone: "",
    adminName: "",
    adminUsername: "",
    adminPassword: "AutoGeneratedSecureTempPass123!"
  });
  const [inquiryErrors, setInquiryErrors] = useState({});
  const [inquirySuccessModal, setInquirySuccessModal] = useState(false);

  // Forgot Password modal
  const [forgotModalOpen, setForgotModalOpen] = useState(false);
  const [forgotEmail, setForgotEmail] = useState("");
  const [resetSent, setResetSent] = useState(false);

  // =========================================================================
  // INSTITUTIONAL SIGN IN SUBMIT
  // =========================================================================
  const handleSignInSubmit = async (e) => {
    e.preventDefault();
    const newErrors = {};
    const trimmedUser = username.trim();

    if (!trimmedUser) {
      newErrors.username = "Please enter your institution username or official email.";
    }
    if (!password) {
      newErrors.password = "Please enter your password.";
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      showWarning("Username and password are required.");
      return;
    }

    setErrors({});
    setLoading(true);
    try {
      const result = await institutionLogin(trimmedUser, password);
      
      // Check if user requires mandatory first-login password change
      if (result.user?.needsPasswordReset) {
        setResetOldPassword(password);
        setPasswordResetModalOpen(true);
        showInfo("First-time login detected. Please set a new permanent password.");
        return;
      }

      showSuccess(`Welcome back, ${result.user?.name || trimmedUser}!`);

      if (result.role === "university_admin") {
        navigate("/institution/dashboard");
      } else if (result.role === "placement") {
        navigate("/placement/dashboard");
      } else if (result.role === "branch_admin") {
        navigate("/admin/students");
      } else {
        navigate("/admin/dashboard");
      }
    } catch (err) {
      const msg = err.message || "Invalid institution credentials.";
      setErrors({ general: msg });
      setPassword("");
      showError(msg);
    } finally {
      setLoading(false);
    }
  };

  // =========================================================================
  // MANDATORY FIRST-LOGIN PASSWORD CHANGE
  // =========================================================================
  const handleFirstLoginPasswordChange = async (e) => {
    e.preventDefault();
    if (!resetNewPassword || resetNewPassword.length < 6) {
      showError("New password must be at least 6 characters long.");
      return;
    }
    if (resetNewPassword !== resetConfirmPassword) {
      showError("New passwords do not match.");
      return;
    }

    try {
      setResettingPassword(true);
      await changePassword(resetOldPassword, resetNewPassword);
      showSuccess("Password updated successfully! Welcome to your institutional console.");
      setPasswordResetModalOpen(false);
      navigate("/institution/dashboard");
    } catch (err) {
      showError(err.message || "Failed to update password. Please try again.");
    } finally {
      setResettingPassword(false);
    }
  };

  // =========================================================================
  // INBOUND PARTNERSHIP INQUIRY SUBMIT
  // =========================================================================
  const handleInquirySubmit = async (e) => {
    e.preventDefault();
    const errs = {};

    if (!inquiryForm.name.trim()) errs.name = "Institution name is required.";
    if (!inquiryForm.officialEmail.trim()) {
      errs.officialEmail = "Official institutional email is required.";
    } else {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(inquiryForm.officialEmail.trim())) {
        errs.officialEmail = "Please enter a valid email address.";
      }
    }
    if (!inquiryForm.city.trim()) errs.city = "City is required.";
    if (!inquiryForm.state.trim()) errs.state = "State is required.";
    if (!inquiryForm.adminName.trim()) errs.adminName = "Primary Dean / Placement Head name is required.";
    if (!inquiryForm.phone.trim()) errs.phone = "Contact phone number is required.";

    if (Object.keys(errs).length > 0) {
      setInquiryErrors(errs);
      showWarning("Please complete all required fields.");
      return;
    }

    setInquiryErrors({});
    setLoading(true);

    try {
      const slug = (inquiryForm.code || inquiryForm.name.slice(0, 4)).toLowerCase().replace(/[^a-z0-9]/g, '');
      const payload = {
        ...inquiryForm,
        code: (inquiryForm.code || inquiryForm.name.slice(0, 4)).toUpperCase(),
        adminUsername: `${slug}_admin`,
        adminPassword: "TempPassword123!"
      };

      await onboardUniversity(payload);
      setInquirySuccessModal(true);
    } catch (err) {
      showError(err.message || "Submission failed. Please try again or contact support.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col justify-between selection:bg-indigo-500 selection:text-white relative overflow-hidden">
      {/* Dynamic Background Glows */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute -top-40 left-1/4 w-96 h-96 bg-indigo-600/15 rounded-full blur-3xl" />
        <div className="absolute top-1/2 right-10 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl" />
        <div className="absolute -bottom-20 left-10 w-80 h-80 bg-blue-600/10 rounded-full blur-3xl" />
      </div>

      {/* Header */}
      <header className="relative z-10 w-full max-w-7xl mx-auto px-6 py-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-indigo-600 to-indigo-400 flex items-center justify-center shadow-lg shadow-indigo-600/25 border border-indigo-400/30">
            <Building2 className="w-5 h-5 text-white" />
          </div>
          <div>
            <span className="text-lg font-black tracking-tight bg-gradient-to-r from-white via-slate-200 to-indigo-200 bg-clip-text text-transparent">
              FLASH SIPS
            </span>
            <span className="block text-[10px] font-semibold uppercase tracking-widest text-indigo-400/90 font-mono">
              Institutional Governance
            </span>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {isRegisterMode ? (
            <button
              onClick={() => setIsRegisterMode(false)}
              className="text-xs font-semibold text-slate-300 hover:text-white px-4 py-2 rounded-xl bg-slate-900/80 border border-slate-800 hover:border-slate-700 transition-all cursor-pointer"
            >
              Sign In to Console &rarr;
            </button>
          ) : (
            <button
              onClick={() => setIsRegisterMode(true)}
              className="text-xs font-semibold text-indigo-400 hover:text-indigo-300 px-4 py-2 rounded-xl bg-indigo-950/40 border border-indigo-800/50 hover:border-indigo-700 transition-all cursor-pointer"
            >
              Partner With Us &rarr;
            </button>
          )}
        </div>
      </header>

      {/* Main Container */}
      <main className="relative z-10 flex-1 flex items-center justify-center px-4 py-8">
        {!isRegisterMode ? (
          /* ========================================================================= */
          /* SIGN IN CARD                                                              */
          /* ========================================================================= */
          <div className="w-full max-w-md">
            <div className="bg-slate-900/90 backdrop-blur-xl border border-slate-800/90 rounded-3xl p-8 shadow-2xl shadow-black/60 relative overflow-hidden">
              <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-blue-500" />

              <div className="mb-8 text-center">
                <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-semibold mb-3">
                  <ShieldCheck className="w-3.5 h-3.5" />
                  Institutional Sign In
                </div>
                <h1 className="text-2xl font-bold tracking-tight text-white">
                  Institutional Console
                </h1>
                <p className="text-xs text-slate-400 mt-1.5 leading-relaxed">
                  Sign in as College Admin, T&P Officer, Department HOD, or Branch Coordinator.
                </p>
              </div>

              {errors.general && (
                <div className="mb-6 p-3.5 bg-rose-500/10 border border-rose-500/20 rounded-xl flex items-start gap-2.5 text-xs text-rose-300">
                  <AlertCircle className="w-4 h-4 shrink-0 text-rose-400 mt-0.5" />
                  <span>{errors.general}</span>
                </div>
              )}

              <form onSubmit={handleSignInSubmit} className="space-y-4">
                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                    Username / Official Email
                  </label>
                  <div className="relative">
                    <User className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
                    <input
                      type="text"
                      value={username}
                      onChange={(e) => {
                        setUsername(e.target.value);
                        if (errors.username) setErrors((prev) => ({ ...prev, username: null }));
                      }}
                      placeholder="e.g. mit_admin, iit_tpo, cse_coord"
                      className="w-full bg-slate-950/80 border border-slate-800 rounded-xl pl-10 pr-4 py-2.5 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all"
                    />
                  </div>
                  {errors.username && (
                    <p className="text-[11px] text-rose-400 mt-1">{errors.username}</p>
                  )}
                </div>

                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className="block text-xs font-semibold text-slate-300">
                      Password
                    </label>
                    <button
                      type="button"
                      onClick={() => setForgotModalOpen(true)}
                      className="text-[11px] font-semibold text-indigo-400 hover:text-indigo-300 transition-colors"
                    >
                      Forgot password?
                    </button>
                  </div>
                  <div className="relative">
                    <Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
                    <input
                      type={showPassword ? "text" : "password"}
                      value={password}
                      onChange={(e) => {
                        setPassword(e.target.value);
                        if (errors.password) setErrors((prev) => ({ ...prev, password: null }));
                      }}
                      placeholder="••••••••••••"
                      className="w-full bg-slate-950/80 border border-slate-800 rounded-xl pl-10 pr-10 py-2.5 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all"
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300"
                    >
                      {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    </button>
                  </div>
                  {errors.password && (
                    <p className="text-[11px] text-rose-400 mt-1">{errors.password}</p>
                  )}
                </div>

                <div className="flex items-center justify-between text-xs pt-1">
                  <label className="flex items-center gap-2 cursor-pointer select-none text-slate-400 hover:text-slate-300">
                    <input
                      type="checkbox"
                      checked={rememberMe}
                      onChange={(e) => setRememberMe(e.target.checked)}
                      className="w-4 h-4 rounded bg-slate-950 border-slate-800 text-indigo-600 focus:ring-indigo-500/20"
                    />
                    Remember session
                  </label>
                </div>

                <Button
                  type="submit"
                  variant="primary"
                  fullWidth
                  loading={loading}
                  className="py-3 mt-4 text-sm font-bold bg-indigo-600 hover:bg-indigo-500 shadow-lg shadow-indigo-600/30"
                >
                  Sign In to Console
                </Button>
              </form>

              <div className="mt-8 pt-6 border-t border-slate-800/80">
                <div className="bg-slate-950/60 border border-slate-800/60 rounded-xl p-3 text-[11px] text-slate-400 leading-relaxed">
                  <span className="font-semibold text-slate-200">Role-Based Access:</span> Master College Admins manage academic departments; TPO officers manage universal placements & drives; Branch Coordinators control student CRUD and coding arena toggles.
                </div>
              </div>
            </div>
          </div>
        ) : (
          /* ========================================================================= */
          /* INBOUND PARTNERSHIP BRIEFING / DECK INQUIRY                               */
          /* ========================================================================= */
          <div className="w-full max-w-2xl">
            <div className="bg-slate-900/90 backdrop-blur-xl border border-slate-800/90 rounded-3xl p-8 shadow-2xl shadow-black/60 relative overflow-hidden">
              <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-blue-500" />

              <div className="mb-6">
                <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-300 text-xs font-semibold mb-2">
                  <GraduationCap className="w-3.5 h-3.5" />
                  Institutional Partnership Inquiry
                </div>
                <h1 className="text-2xl font-bold tracking-tight text-white">
                  Bring SIPS to Your Institution
                </h1>
                <p className="text-xs text-slate-400 mt-1 leading-relaxed">
                  Fill in your institutional details below. Our enterprise academic alignment team will review your requirements, coordinate discussions, and provision your college governance workspace.
                </p>
              </div>

              <form onSubmit={handleInquirySubmit} className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      Institution / College Name *
                    </label>
                    <input
                      type="text"
                      value={inquiryForm.name}
                      onChange={(e) => setInquiryForm({ ...inquiryForm, name: e.target.value })}
                      placeholder="e.g. National Institute of Engineering"
                      className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500"
                    />
                    {inquiryErrors.name && <p className="text-[10px] text-rose-400 mt-1">{inquiryErrors.name}</p>}
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      College Code / Abbreviation
                    </label>
                    <input
                      type="text"
                      value={inquiryForm.code}
                      onChange={(e) => setInquiryForm({ ...inquiryForm, code: e.target.value })}
                      placeholder="e.g. NIE, MIT, RVCE"
                      className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500 uppercase"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      Official Institutional Email *
                    </label>
                    <input
                      type="email"
                      value={inquiryForm.officialEmail}
                      onChange={(e) => setInquiryForm({ ...inquiryForm, officialEmail: e.target.value })}
                      placeholder="e.g. tpo@nie.ac.in"
                      className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500"
                    />
                    {inquiryErrors.officialEmail && <p className="text-[10px] text-rose-400 mt-1">{inquiryErrors.officialEmail}</p>}
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      Contact Phone / Dean Phone *
                    </label>
                    <input
                      type="tel"
                      value={inquiryForm.phone}
                      onChange={(e) => setInquiryForm({ ...inquiryForm, phone: e.target.value })}
                      placeholder="+91 98765 43210"
                      className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500"
                    />
                    {inquiryErrors.phone && <p className="text-[10px] text-rose-400 mt-1">{inquiryErrors.phone}</p>}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      Dean / TPO Officer Name *
                    </label>
                    <input
                      type="text"
                      value={inquiryForm.adminName}
                      onChange={(e) => setInquiryForm({ ...inquiryForm, adminName: e.target.value })}
                      placeholder="e.g. Dr. Rajesh Kumar"
                      className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500"
                    />
                    {inquiryErrors.adminName && <p className="text-[10px] text-rose-400 mt-1">{inquiryErrors.adminName}</p>}
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-slate-300 mb-1">
                      City & State *
                    </label>
                    <div className="grid grid-cols-2 gap-2">
                      <input
                        type="text"
                        value={inquiryForm.city}
                        onChange={(e) => setInquiryForm({ ...inquiryForm, city: e.target.value })}
                        placeholder="City"
                        className="bg-slate-950/80 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500"
                      />
                      <input
                        type="text"
                        value={inquiryForm.state}
                        onChange={(e) => setInquiryForm({ ...inquiryForm, state: e.target.value })}
                        placeholder="State"
                        className="bg-slate-950/80 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500"
                      />
                    </div>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    Website URL
                  </label>
                  <input
                    type="url"
                    value={inquiryForm.website}
                    onChange={(e) => setInquiryForm({ ...inquiryForm, website: e.target.value })}
                    placeholder="https://www.nie.ac.in"
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-indigo-500"
                  />
                </div>

                <Button
                  type="submit"
                  variant="primary"
                  fullWidth
                  loading={loading}
                  className="py-3 mt-4 text-xs font-bold bg-purple-600 hover:bg-purple-500 shadow-lg shadow-purple-600/30"
                >
                  Submit Institutional Briefing Request &rarr;
                </Button>
              </form>
            </div>
          </div>
        )}
      </main>

      {/* Mandatory First-Login Password Reset Modal */}
      <Modal
        isOpen={passwordResetModalOpen}
        onClose={() => {}} // Non-dismissible until password reset
        title="Security Notice: Set Permanent Password"
      >
        <form onSubmit={handleFirstLoginPasswordChange} className="space-y-4 pt-2">
          <div className="p-3.5 bg-amber-500/10 border border-amber-500/20 rounded-xl flex items-start gap-2.5 text-xs text-amber-300">
            <KeyRound className="w-4 h-4 shrink-0 text-amber-400 mt-0.5" />
            <span>
              This is your first time logging in with auto-generated credentials. Please choose a strong, confidential password for your account.
            </span>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">
              New Password (min 6 characters)
            </label>
            <input
              type="password"
              value={resetNewPassword}
              onChange={(e) => setResetNewPassword(e.target.value)}
              placeholder="••••••••••••"
              required
              minLength={6}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-sm text-white focus:outline-none focus:border-indigo-500"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1">
              Confirm New Password
            </label>
            <input
              type="password"
              value={resetConfirmPassword}
              onChange={(e) => setResetConfirmPassword(e.target.value)}
              placeholder="••••••••••••"
              required
              minLength={6}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-sm text-white focus:outline-none focus:border-indigo-500"
            />
          </div>

          <Button
            type="submit"
            variant="primary"
            fullWidth
            loading={resettingPassword}
            className="py-2.5 font-bold"
          >
            Update Password & Access Console
          </Button>
        </form>
      </Modal>

      {/* Inquiry Registered Modal */}
      <Modal
        isOpen={inquirySuccessModal}
        onClose={() => {
          setInquirySuccessModal(false);
          setIsRegisterMode(false);
        }}
        title="Institutional Briefing Registered"
      >
        <div className="text-center py-4 space-y-4">
          <div className="w-12 h-12 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto">
            <CheckCircle2 className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white">Details Received</h3>
            <p className="text-xs text-slate-400 mt-1 max-w-sm mx-auto leading-relaxed">
              Our Super Admin Enterprise Team has received your inquiry. We will contact your Placement Cell / Dean to align on institutional tiers and dispatch your Master and TPO credentials.
            </p>
          </div>
          <Button
            variant="primary"
            onClick={() => {
              setInquirySuccessModal(false);
              setIsRegisterMode(false);
            }}
            className="text-xs font-semibold"
          >
            Return to Sign In
          </Button>
        </div>
      </Modal>

      {/* Forgot Password Modal */}
      <Modal
        isOpen={forgotModalOpen}
        onClose={() => {
          setForgotModalOpen(false);
          setResetSent(false);
        }}
        title="Reset Institutional Password"
      >
        <div className="space-y-4 pt-2">
          {resetSent ? (
            <div className="p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-xl text-center">
              <CheckCircle2 className="w-8 h-8 text-emerald-400 mx-auto mb-2" />
              <p className="text-xs text-slate-300">
                Password recovery instructions dispatched to <strong className="text-white">{forgotEmail}</strong>. Please check your inbox.
              </p>
            </div>
          ) : (
            <>
              <p className="text-xs text-slate-400">
                Enter your institutional admin username or registered official email address.
              </p>
              <input
                type="text"
                value={forgotEmail}
                onChange={(e) => setForgotEmail(e.target.value)}
                placeholder="e.g. tpo@college.edu or college_admin"
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-indigo-500"
              />
              <Button
                variant="primary"
                fullWidth
                onClick={() => setResetSent(true)}
                className="py-2.5 text-xs font-bold"
              >
                Send Recovery Instructions
              </Button>
            </>
          )}
        </div>
      </Modal>

      {/* Footer */}
      <footer className="relative z-10 w-full max-w-7xl mx-auto px-6 py-4 flex flex-col sm:flex-row items-center justify-between text-[11px] text-slate-500 border-t border-slate-900">
        <p>&copy; {new Date().getFullYear()} Flash Innovations Inc. All institutional rights reserved.</p>
        <div className="flex items-center gap-4 mt-2 sm:mt-0">
          <a href="/privacy" className="hover:text-slate-400 transition-colors">Privacy Policy</a>
          <a href="/terms" className="hover:text-slate-400 transition-colors">Terms of Governance</a>
          <a href="/security" className="hover:text-slate-400 transition-colors">Data Security</a>
        </div>
      </footer>
    </div>
  );
}
